version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    environment:
      - APP_ID: <INSERT-APP-ID>
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apt-get update
            apt-get -y install python3 pip3
            # You can also install Yarn, NPM, or anything else you need to use to build and test your extension.
      - run:
          name: "Install archive all"
          command: pip3 install git-archive-all
      - run:
          name: "Package Extension"
          command: git-archive-all --force-submodules "ext.zip"
      - store_artifacts:
          path: ext.zip
          destination: ext.zip